export const sites = [
  {
    c: "AI",
    d: "www.t3.chat",
    r: 0,
    s: "T3 Chat",
    sc: "AI",
    t: "t3",
    u: "https://www.t3.chat/new?q={{{s}}}",
  },{
    c: "Online Services",
    d: "google.com",
    r: 0,
    s: "Google Search 100 Results",
    sc: "Search",
    t: "g100",
    u: "http://google.com/search?q={{{s}}}&tbo=1&num=100",
  },
  {
    c: "Online Services",
    d: "www.google.com",
    r: 48,
    s: "Google (Past 24h)",
    sc: "Google",
    t: "g24",
    u: "http://www.google.com/search?q={{{s}}}&tbs=qdr:d",
  },{
    c: "Online Services",
    d: "www.google.com",
    r: 1942262,
    s: "Google",
    sc: "Google",
    t: "g",
    u: "https://www.google.com/search?q={{{s}}}",
  }, {
    c: "Online Services",
    d: "google.com",
    r: 52329,
    s: "Google Images",
    sc: "Google",
    t: "gi",
    u: "https://google.com/search?tbm=isch&q={{{s}}}&tbs=imgo:1",
  },{
    c: "Online Services",
    d: "search.yahoo.com",
    r: 1614,
    s: "Yahoo!",
    sc: "Search",
    t: "y",
    u: "http://search.yahoo.com/search?p={{{s}}}",
  },{
    c: "Multimedia",
    d: "www.youtube.com",
    r: 463021,
    s: "YouTube",
    sc: "Video",
    t: "yt",
    u: "https://www.youtube.com/results?search_query={{{s}}}",
  },{
    c: "Multimedia",
    d: "music.youtube.com",
    r: 4430,
    s: "Youtube Music",
    sc: "Video",
    t: "ytm",
    u: "https://music.youtube.com/search?q={{{s}}}",
  },  {
    c: "Multimedia",
    d: "duckduckgo.com",
    r: 0,
    s: "DuckDuckGo",
    sc: "DuckDuckGo",
    t: "ddg",
    u: "http://duckduckgo.com/?q={{{s}}}",
  },
]
